allowBuilds:
  esbuild: true
  unrs-resolver: true

overrides:
  esbuild: ^0.28.1
  "minimatch@3>brace-expansion": 1.1.18
  "minimatch@10>brace-expansion": 5.0.9
  "next>postcss": ^8.5.23
  "@tailwindcss/postcss>postcss": ^8.5.23
  "next>sharp": 0.35.0
